### ISSUE TITLE
Wallet thinks it is synced but it is not after internet connection drops

### ISSUE THREAD

**Issue by ahatstat** [Nexusoft/NexusInterface#114]
A wallet can appear to be synchronized (blue check mark) even though it is not after a loss of internet connection.  After the internet connection is restored, the wallet continues to display the blue check, but no additional blocks are processed.   Restarting the wallet fixes the problem but the user may not realize there is a problem for a long time causing loss of staking rate and reduced network participation.  The desired behavior would be for the wallet to catch up after the connection returns or and/or display some indicator that the wallet is out of sync.   I observed this on two wallets on Ubuntu with wallet version 2.13.

**Comment by KenCorma** [comment]
Yeah I have experienced some of this too when I go in and out of sleep mode on my laptop. I'll work with the team to  find a solution.
