### ISSUE TITLE
Trying to login before wallet has synced

### ISSUE THREAD

**Issue by joehuggans** [Nexusoft/NexusInterface#115]
Trying to login before wallet has synced (past the position in the block chain where you registered) gives an error which feels like an incorrect username/password.

This is going to be highly stressful experience for most people who would assume that they have made an error copying down their credentials.

Can logging in be disabled until wallet has synced or a message be displayed on the login form when the wallet isn't synced to tell the user that if their login fails this is why.

Or on the error message tell them this.

Or allow user to submit username/password/pin but delay response until wallet has synced - as suggested by cryptonit

**Comment by Qrysto** [comment]
The error messages are given by the core. @paulscreen could we add something to the "Invalid credentials" error message (@joehuggans was that the error you got?) like "Invalid credentials or blockchain has not yet synced up"?

**Comment by joehuggans** [comment]
The error was - 
Error logging in 
Invalid credentials

**Comment by KenCorma** [comment]
We assume the credentials are invalid but if you not in sync we throw an additional warning that suggests to be fully synced.

**Comment by joehuggans** [comment]
Great work!
