### ISSUE TITLE
referral links in API Documentation submenus not working

### ISSUE THREAD

**Issue by Kaslion** [Nexusoft/NexusInterface#117]
When in the API documentation section and you go to one of the sections (e.g. assets) under "Methods" there is a summary of all APIs in this section. You can press the links (e.g. create/asset) and would expect to go to the documentation of create/asset. Instead nothing happens in the documentation, but in the background the wallet goes from console back to the starting screen with the globe.

**To Reproduce**
- go to console
- go to API documentation
- press one of the sections (e.g. assets, finance, legder, etc)
- Scroll to Methods
- press one of the commands

**Expected behavior**
 expect to go to the documentation of selected API command.

**Desktop (please complete the following information):**

- OS: Win10
Wallet version 2.2.0

Nexs Core version 4.1.3 Tritium CLI [LLD][x64]

**Comment by bibbityjibbity** [comment]
Commit 8728d1faa9fe71745984a296ff8ed256351f89e5 patched this and will be included in 3.0.0+
