### ISSUE TITLE
SHA512sum is incorrect on nexus_wallet-Linux-3.0.3.AppImage

### ISSUE THREAD

**Issue by hobbit6** [Nexusoft/NexusInterface#124]
For file: nexus_wallet-Linux-3.0.3.AppImage

SAH512sum on release page has:
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

Actually it is:
fd872bc872f37e5d7c54caaa0df17d74ebf989a50bd2d89a8f548f7176a468561c43c523b2ef659b281dd3484b1f11f0ab4a2034ef92350f73777e7ce5d2a63f

Please confirm that this is mistake or if the file has been tampered.

**Comment by KenCorma** [comment]
This was a mistake, as you can see the Appimage checksum and the Windows Installer exe are the same. There was a mistake in writing the hashes. I have verified with my build folder on my machine which is untouched and I can confirm the hash should be 
fd872bc872f37e5d7c54caaa0df17d74ebf989a50bd2d89a8f548f7176a468561c43c523b2ef659b281dd3484b1f11f0ab4a2034ef92350f73777e7ce5d2a63f

**Comment by KenCorma** [comment]
Thank you for bring this to our attention , I have changed the release tab as well as our medium.
