### ISSUE TITLE
"Send to" address book not available without populating the "Send from" field

### ISSUE THREAD

**Issue by hoodat432** [Nexusoft/NexusInterface#130]
In the wallet send section a user is unable to select a "send to" entry from the address book unless a "send from" address is selected.  The address book on the "send to" line appears empty until this is done.  User in slack indicated this is an annoyance and requested a fix. 

**To Reproduce**
If applicable steps to reproduce the behavior:

1. go to wallet send section
2. immediately select the "send to" field and address book will indicate it is empty even though it is not. 
3. add a "send from" address, then go back to "send to" and address book will be available.

**Expected behavior**
Address book should be available from "send to" without entering a "send from" address.

**Desktop (please complete the following information):**

- OS: Ubuntu 10
- Wallet Version 3.03
- Core 5.0.3

**Comment by Qrysto** [comment]
This issue will be fixed in the next release
