### ISSUE TITLE
Simplified Version,汉语.

### ISSUE THREAD

**Issue by KenCorma** [Nexusoft/NexusInterface#18]
Name it zh.json

**Comment by ceozero** [comment]
![QQ图片20190525161624](https://user-images.githubusercontent.com/22513657/58366684-84716280-7f08-11e9-966d-4bc3bda5dfad.png)
![QQ图片20190525161643](https://user-images.githubusercontent.com/22513657/58366685-85a28f80-7f08-11e9-9301-4cbb6ff55105.png)

**Comment by KenCorma** [comment]
> ![QQ图片20190525161624](https://user-images.githubusercontent.com/22513657/58366684-84716280-7f08-11e9-966d-4bc3bda5dfad.png)
> ![QQ图片20190525161643](https://user-images.githubusercontent.com/22513657/58366685-85a28f80-7f08-11e9-9301-4cbb6ff55105.png)

THANK YOU!

If you want to either fork the repo and add let me do a pull request or attach the translation file into this thread. I will take care of it.

**Comment by KenCorma** [comment]
Please go here for translating 
https://crwd.in/nexus-interface

**Comment by KenCorma** [comment]
Project Done 
https://crowdin.com/project/nexus-interface/zh-CN#
