### ISSUE TITLE
Very high CPU usage with Desktop wallet build 3.1.0-testnet-9 appimage for linux

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#191]
Running the desktop wallet on linux, found very high CPU usage almost 45-50% on a Ryzen 7 5800 8 core CPU. The wallet was tested in the lite mode.

![Ryzen7-5800](https://user-images.githubusercontent.com/84140911/228146374-191714d9-627f-4997-a684-0f796dc37a73.jpeg)

**Comment by Aeonwise** [comment]
The desktop wallet CPU usage is high and the exact file shown is nexus-linux-x64  

![Wallet-CPU-usage](https://user-images.githubusercontent.com/84140911/228158925-b611289d-1712-4dd0-81a3-e9eb35ceb7ba.png)

![Hardware-specs](https://user-images.githubusercontent.com/84140911/228159374-13be2b9c-216a-4884-8522-57284465063e.png)

**Comment by Qrysto** [comment]
What was the wallet doing while the CPU usage was this high? Was it idle?
Also, could you identify if the CPU usage was from the core or from the UI?

**Comment by Qrysto** [comment]
@Aeonwise Can you help me do this: set the Verbose level to 3 in the Core Settings, run the wallet for a few minutes (while the CPU usage is high), then send me the 0.log in testnet1/client folder? (assuming you're running on testnet 1 lite mode)

**Comment by VidereLicet** [comment]
CPU usage can be high when synchronizing, but yes as @Qrysto said we need better data than this. Need you to provide details such as how long you tested with high CPU, was it right after startup, does it persist, does it go away, what are logs on verbose=3.

**Comment by Aeonwise** [comment]
> @Aeonwise Can you help me do this: set the Verbose level to 3 in the Core Settings, run the wallet for a few minutes (while the CPU usage is high), then send me the 0.log in testnet1/client folder? (assuming you're running on testnet 1 lite mode)

I changed the verbose level to 3 and now the high CPU usage issue has resolved itself and to check removed the verbose=3 flag and then changed between lite and full modes, even restarted the wallet a few times.

The issue has disappeared.

**Comment by VidereLicet** [comment]
Was fixed with commit 0ef5d8df303d400dc235262a99fccfdedfa64edd
