### ISSUE TITLE
Changing from Full Mode to Lite Mode, the Lite mode toggle button was disabled. 

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#195]
Wallet version: Desktop 3.1.0-testnet10. Appimage

Trying to change from full mode to lite mode, the toggle button was disabled (greyed out),  the reason was that in Full mode the multi-user option was  enabled and when its enabled lite mode is disabled.

This may confuse the normal user and should there should be a warning to disable multi-user so as to enable the user to switch to Lite mode.

**Comment by Qrysto** [comment]
Description added
