### ISSUE TITLE
Create new Name popup, clicking on 'Namespaced' the wallet goes blank and freezes

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#196]
Wallet version: Desktop 3.1.0-testnet10. Appimage

Under the User module > Names, clicking on  'Create new Name', and selecting  'Namespaced'  blanks out and freezes the wallet. This happens in both lite and full mode.

https://user-images.githubusercontent.com/84140911/229989670-2d32dddf-4642-4182-97ed-b61653faeba3.mp4

**Comment by Qrysto** [comment]
Fixed
