### ISSUE TITLE
Sending transaction results in "Failed to accept. [1mAccept[0m : CONFLICT: prev tx CONFLICTED 0101e1f136e221b54bdf"

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#199]
Wallet Version: Desktop-3.1.0-testnet10.Appimage

This issue was seen in the Full mode.

Sending NXS coins on test-net from default to trust account gives the error "Failed to accept. [1mAccept[0m : CONFLICT: prev tx CONFLICTED 0101e1f136e221b54bdf"

**This is the log file:**
[0.log](https://github.com/Nexusoft/NexusInterface/files/11208104/0.log)

https://user-images.githubusercontent.com/84140911/231375901-5f655c52-048a-406a-b483-70130f66baf9.mp4

**Comment by Qrysto** [comment]
@Aeonwise Can you confirm if this issue is fixed?
