### ISSUE TITLE
Logging into test-net staking account in Lite mode gives the error "Account does not exist or connection Failed"

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#200]
Wallet Version: Desktop-3.1.0-testnet10.Appimage

Wallet mode: Lite

When logging into the testnet staking account gives the error " Account does not exist or connection Failed".

Logging into the testnet normal account does not give the accounts or other details. 

In Full mode the same accounts log in successfully.

**This is the lite mode log file:**
[0.log](https://github.com/Nexusoft/NexusInterface/files/11208191/0.log)

https://user-images.githubusercontent.com/84140911/231378455-d0963499-d3de-4790-b117-391ceabf72ce.mp4

**Comment by VidereLicet** [comment]
You have nodes that are not configured or upgraded properly. I run client on testnet and I get "-client mode requires version 3060000" which means you are using an outdated protocol version and you most likely do not have lookup protocol ports opened either.
