### ISSUE TITLE
Adjust stake amount does not work in the new 3.1.0 wallet

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#206]
Wallet : 3.1.0 Mac, Linux & windows

After adjusting stake in the new wallet it asks for the PIN and then it shows the message "Stake amount has been updated" but then the pending changes are not shown.

Tried to adjust stake using API from console and the return message shows "success=true", but checking finance/get/stakeinfo does not show the pending changes.

**Comment by Qrysto** [comment]
@VidereLicet Seems like an issue on the core

**Comment by NamecoinGithub** [comment]
I had it show up for me the changes to adjust staking using Linux 3.1 NexusInterface

**Comment by NamecoinGithub** [comment]
I just tried it again with the newly minted staked coins  and it worked as it should, but I am going up in the stake amount are you going lower by chance?

It seems to work fine for me?

**Comment by NexusKing83** [comment]
For me is still isue but i have large sigchain maybe that's why.
i can't see any +amount and not pending change on windows

**Comment by NamecoinGithub** [comment]
Well Nevermind it quit working for me too

It was just a MIRAGE 

It has since disappeared showing the Adjustment AFTER a new Trust transaction occurred a couple Mins ago

**Comment by VidereLicet** [comment]
We sign a piece of data to indicate stake change, issue is being resolved for 5.1.1.

**Comment by NealHelman** [comment]
This worked for me in 3.1.1/5.1.1 remote core

**Comment by KenCorma** [comment]
Is this issue resolved for you?

**Comment by Qrysto** [comment]
This is resolved in 3.1.1
