### ISSUE TITLE
Sending transaction using only sigchain login is not working on desktop, but is working on mobile wallet

### ISSUE THREAD

**Issue by NexusKing83** [Nexusoft/NexusInterface#207]
Hello friends
I would like to inform about one issue on desktop wallet version 3.1.0 core 5.1 
When i send from my desktop wallet with ok Balance trust of default and using only SigChain(login only) it shows me "Recipient name cannot be resolved" and i have to use long address. But on mobile wallet is working perfect. 
Could you check this problem guys.
Thank you
Best wishes

**Comment by NamecoinGithub** [comment]
I am sorry 

"with ok Balance trust of default and using only SigChain(login only) it shows me "Recipient name cannot be resolved" and i have to use long address."

Makes no sense what you are explaining

**Comment by NexusKing83** [comment]
Ok try to send NXS to someone on Desktop wallet useing only sigchain not full adres long like BTC has.
Now you see issue ? 
"Recipient name cannot be resolved"
i have to give full address to send anyone on desktop wallet NXS.
mobile wallet is ok because you can send NXS to anyone with sigchain just only login not long address

**Comment by NamecoinGithub** [comment]
Well if your trying to send to the Username of someone it's all case sensitive and the trust and default have to all be lower case letters

Username:trust
Username:default

**Comment by NamecoinGithub** [comment]
Yes I just tested this on Desktop

It shows that Error if you have the wrong credentials, but when I typed 

Tesla:trust 

the address shows up fine

You have to have the Semi-Colin :

**Comment by NexusKing83** [comment]
ahh ok sorry now is working with that. i didn't know about this i thought that it will find sigchain just like that ;)

**Comment by NamecoinGithub** [comment]
That is a new function it actually shows the Sigchain now, the Old wallet it would not show if you had it correct or not until you tried sending it would throw the error message if you got something wrong!
