### ISSUE TITLE
Send Module, clicking on NXS amount - ALL the wallet freezes

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/NexusInterface#208]
Wallet Interface= 3.1.0 ALL versions

In the send module when clicking on NXS amount input (ALL) the wallet freezes and turns fully black. Only solution is to restart the wallet.

![2023-04-28 00 06 27](https://user-images.githubusercontent.com/84140911/234959999-9fc7fa0f-96ff-4d3b-94fe-35d3d29a0c55.jpg)

**Comment by NamecoinGithub** [comment]
LOL, can confirm this I shouldn't have tried it but ya that's a Bug

**Comment by NamecoinGithub** [comment]
https://github.com/Nexusoft/NexusInterface/commit/4fa77f5ae93145fc7c8d0a1a15c6df44c292537c

Qrysto got ya covered already
