### ISSUE TITLE
Maybe LLLTao issue but New Stake Blocks don't show up in Transactions

### ISSUE THREAD

**Issue by NamecoinGithub** [Nexusoft/NexusInterface#209]
The balance is there I have staked a few blocks using 3.1 but in the Transaction tab they aren't showing up
![Skærmbillede på 2023-04-27 19-30-52](https://user-images.githubusercontent.com/130555019/234971947-becd1f7b-68d6-4fa3-80ff-69594322fd5a.png)
 Until Clicking Operations and clicking any of the different types and than moving back to ALL seems to solve the issue of missing new Trust transactions

But that is merely a temporary fix, as I don't think it's a desirable thing to do

**Comment by KenCorma** [comment]
The issue is from the core not telling the UI to refresh, at least the way it worked before. We have made some changes and with 3.1.1 you should see the transaction pool update more ofter.
