### ISSUE TITLE
Market Price & Market Cap No Longer Display

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/NexusInterface#211]
**Description**
The Market Price shows an underline, and the Market Cap shows $NaN.

**Reproduce the Issue**
All I had to do to reproduce the error was restart the wallet.

**Expected behavior**

**Screenshots**
![image](https://github.com/Nexusoft/NexusInterface/assets/22264290/1611b945-95d1-4102-95ea-0f0471553c3f)

**Desktop (please complete the following information):**

- Reported on Windows and Mac
- Wallet Version  3.1.0
- Daemon Version 5.1.0

**Comment by Qrysto** [comment]
Price and 24h change data have been fixed for v3.1.0
