### ISSUE TITLE
Incoming Balances NXS showing without any transactions. No transfer to wallet and showing 81k NXS

### ISSUE THREAD

**Issue by NexusKing83** [Nexusoft/NexusInterface#212]
Hello
I would like to report issue on new wallet 3.1.0 
Windows 
This issue is on my friend computer
Incoming Balances 81357,443 NXS but nobody did any transactions. 
i heard also from some others people they have same issue. 
Without any transactions showing me Incoming Balances.
![20230527_120226](https://github.com/Nexusoft/NexusInterface/assets/129859665/1842b39a-02d7-4210-9191-9601d1777f80)

**Comment by NamecoinGithub** [comment]
Wow, it must have been a Donation from a Twitter Follower if they know your Nexus ID to send to!  

Did it get Confirmations?

**Comment by NamecoinGithub** [comment]
Is getting Random NXS sent to someone still an Issue going on?

**Comment by Qrysto** [comment]
@NexusKing83 Is this issue still happening?

**Comment by KenCorma** [comment]
Have you experienced this issue with 3.1.1 ?

**Comment by Qrysto** [comment]
Most likely this is resolved in 3.1.1. If not, please just reopen.
