### ISSUE TITLE
Transaction History not reloading

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/NexusInterface#218]
The Transaction history doesn't consistently reload.  Got a Trust transaction, but it didn't register in the Transaction history list.  Logged off and back on, and it was in the list.

**Desktop (please complete the following information):**

- OS: Windows
- Wallet Version 3.1.1
- Daemon Version 5,1.1 (remote)

**Comment by Qrysto** [comment]
@VidereLicet I get this issue too. Trust transactions don't show up in the list, even when I log out and log back in. They're missing from the API call result (finance/transactions/any?address=...)

**Comment by NealHelman** [comment]
This is still happening for TRUST transactions using 3.1.1b7/5.1.1rc7 remote core.  I believe DEBITs and CREDITs are coming through.

**Comment by NealHelman** [comment]
This has been fixed in 5.1.1rc11
