### ISSUE TITLE
1-Minute Expiry Sent to Core as 1-Week Expiry

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/NexusInterface#220]
When I create a DEBIT transaction using the Advanced options to set a 60-second expiry, the wallet displays 1-minute (60 seconds) on the confirmation screen, but the contract conditions  still indicate 1 week expiry.

(caller.genesis != 0xa12e7a020c374f20b40a3666dd4b827a3d0ec66c8fd7ac1e4f1d22f28c5dbbef AND contract.timestamp + 604800 > ledger.timestamp) OR (caller.genesis == 0xa12e7a020c374f20b40a3666dd4b827a3d0ec66c8fd7ac1e4f1d22f28c5dbbef AND contract.timestamp + 604800 < ledger.timestamp)

- OS: Windows
- Wallet Version 3.1.1
- Daemon Version 5.1.1-rc7 (remote node)

**Comment by ceozero** [comment]
where can download 3.1.1 ??

**Comment by NealHelman** [comment]
> where can download 3.1.1 ??

Join the Nexus Beta Testers group at https://t.me/+n6JigN2uFttiMmUx

**Comment by NealHelman** [comment]
This is resolved in the 3.1.1-Beta10 wallet.
