### ISSUE TITLE
3.1.1 Fresh Blockchain Sync Fails Everytime @ same Block 342,615

### ISSUE THREAD

**Issue by NamecoinGithub** [Nexusoft/NexusInterface#226]
**Describe the bug**
3.1.1 Fresh Blockchain Sync Fails Everytime @ same Block 342,615

**To Reproduce**
Deleted .nexus blockchain data and fresh Sync

**Screenshots**

![Skærmbillede på 2023-12-31 08-42-17](https://github.com/Nexusoft/NexusInterface/assets/130555019/997df31a-4780-469c-a74f-fc0b768498b1)

**Additional context**

I have tried Multiple times deleting and starting again and it hasn't got past this Block

I had 1 Device that was able to use the Old Blockchain without deleting it, and Connect and Sync using 3.1.1 but not From a Fresh Sync using 3.1.1 on Multiple Computers

And it's still a low 6 Connections for the 3.1.1 that does Sync from Old Blockchain data

This is using Linux Wireguard

**Comment by NamecoinGithub** [comment]
Forgot also, restarting Wallet doesn't help this problem!

**Comment by Qrysto** [comment]
It was synchronizing without bootstrapping right?

**Comment by NamecoinGithub** [comment]
Well, I am afraid to think of what I think happened, but it's more like a Hard Fork @ that Block being enforced somehow within the Code, I am sure it only shows up using a Wireguard VPN, as I have other tests but not on 3.1.1. that I have done and usually that is the case, but it has never NOT Synced from a Fresh Start, previous it only Choked out the Total Connections using a VPN, not Hard Forking!

There is Zero Syncing going on past that Block, and the fact that there are Connections is ODD, if I understand you correctly

But as I said I had 1 Device that was able to Bypass that "Hard Fork" and work using a VPN using the Already Downloaded under the 3.1.0 Wallet!

But it still has the previous Low Connections using a VPN from 3.1.0

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by NamecoinGithub** [comment]
https://github.com/Nexusoft/LLL-TAO/issues/157

![Skærmbillede på 2024-01-04 07-05-18](https://github.com/Nexusoft/NexusInterface/assets/130555019/1e3c50ce-d251-43c7-92a2-e3cdab240970)


I got the LLL-TAO to compile from Source, and it throws the same Hard Fork @ the same Block 342,615 using the LLL-Tao Source node from Fresh Sync, so it's not maybe a Nexus Interface issue as I suspected earlier!

**Comment by KenCorma** [comment]
Can you check again with the latest?

**Comment by NamecoinGithub** [comment]
Yes, I did already, sorry I didn't update it here, but I am going to close this one or let me know which is best to follow!  I think there is good info on Both, but I will update the LLL-Tao issue! 

Thanks

https://github.com/Nexusoft/LLL-TAO/issues/159
