### ISSUE TITLE
ENHANCEMENT: UI lock with password protection

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/NexusInterface#232]
We have had multiple requests to be able to lock the UI with password protection while still staking.

**Comment by NamecoinGithub** [comment]
Good Idea! 

As long as it's understood to Hide the Balance Screen ect...............The Pin is the current "Password Protection" but it would be a much better setup to Hide the Balances from certain threats as Well!  And this Password could be made simple enough and the Pin still protect the Balance with a Complex Password!

**Comment by NamecoinGithub** [comment]
I just thought of another threat this will be Key as well if someone could install Infected Nexus Modules without having to Use the Pin password is a Threat this would Correct!

**Comment by KenCorma** [comment]
Please take a look at the updated branch. 

https://github.com/Nexusoft/NexusInterface/tree/feature/pin-lock
