### ISSUE TITLE
Windows 10 1.0.1 wallet random network disconnect

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [Nexusoft/NexusInterface#50]
Wallet: Tritum 1.0.1
Daemon: built-in 3.0.1
OS: windows 10

Basic Issue Info:
I managed to get the wallet to fully load, and accept my old wallet.dat file. Once fully synced I unlocked for minting, and even recieved a stake. However, at least once per day i notice if i hover over the "block count" and see the last block time, its at least an hour old, sometimes more if i havent had time to check.
This causes the block weight to rise quickly and gets it up to 100% within ia few days, causing me to be penalized and loose my valuable stake rate.

To reproduce:
Fully load a staking wallet, unlock for staking and mining only, and wait 5-24 hours.

Behaviour:
The wallet shows fully synced. shows staking info and balance. however if you check the block count against a block explorer, or just hover and see last block time you will see the wallet is obviously out of date.

Workaround:
Rebooting the wallet seems to fix the issue, however you gain block weight and get closer to penalization by loss of stake rate every single time it happens.

Possible Fix:
Would it be possible to maybe add an addnode function back into the wallet so we can manually add known good nodes? Should i be forwarding the P2P port?

Any suggestions would be greatly appreciated.

**Comment by KenCorma** [comment]
Possible Fix with Nexus Daemon 3.0.2

**Comment by l8nit3tr0ubl3** [comment]
Is there instructions somewhere in updating just the daemon? Or is it done within the wallet? I am currently not running the daemon standalone, it's simply the bundled wallet.

**Comment by KenCorma** [comment]
You can either wait for the wallet to update when we push out a update, or clone the daemon repo and build the daemon yourself, then replacing the one in the Cores folder (you must name it the same).

**Comment by KenCorma** [comment]
We have discovered a deadlock on the backend that will make it so it gets stuck on syncing and it would need a reset, We are currently working on a fix.

**Comment by l8nit3tr0ubl3** [comment]
testing 3.0.1 wallet built with 3.0.2 core now, will update if it fixes, or if bugs are found.

**Comment by Qrysto** [comment]
@l8nit3tr0ubl3 Nice :)
