### ISSUE TITLE
nexus_wallet-Linux-1.1.0.deb doesn't work - critical error

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#55]
**Describe the bug**
Just installed nexus_wallet-Linux-1.1.0.deb on Linux MX (Debian Stretch with improved GUI). Wallet fails with critical error.

**To Reproduce**
```
$ nexus_wallet 
[22403:0720/132833.949305:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Nexus Wallet/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

This is stock Linux, nothing has been changed and I have no knowledge of any custom changed made to sandbox helper or whatever that is.

**Expected behavior**
nexus-wallet command should start wallet 

**Screenshots**
not required

**Desktop (please complete the following information):**
$ uname -a
Linux mx 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	MX
Description:	MX 18.3 Continuum
Release:	18.3
Codename:	Continuum

All packages are from Debian Stretch.

**Comment by pioruns** [comment]
Please note, previous version of the wallet has worked on this machine without this error (Window worked and GUI was present, but wallet failed to synchronize). This is potentially a regression from previous version.

**Comment by Qrysto** [comment]
@KenCorma could you verify this and the AppImage issue on Linux?

**Comment by l8nit3tr0ubl3** [comment]
Possible explanation here: [electron 5.xx issue](https://github.com/Nexusoft/NexusInterface/issues/56#issuecomment-515594077)

**Comment by pioruns** [comment]
Just installed Debian 10 Buster on AMD64 machine. Nexus .deb package can't even be installed, reason:
```
$ sudo gdebi nexus_wallet-Linux-1.1.0.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: gir1.2-gnomekeyring-1.0
```
```
$ apt search gir1.2-gnomekeyring-1.0
Sorting... Done
Full Text Search... Done
```


Package on which Nexus-wallet is dependant on, doesn't even exist in Debian 10 Buster.

**Comment by l8nit3tr0ubl3** [comment]
https://github.com/Foundry376/Mailspring/issues/998#issuecomment-508482010

Again, not a wallet issue, but an issue with a depreciating dependency. But the link above should fix that issue. However, it still will error out due to the electron builder issue.

**Comment by pioruns** [comment]
Why this is not tagged as BUG? Why no one is assigned to this issue?

**Comment by KenCorma** [comment]
Closing this as the resolve is the same as Appimage
