### ISSUE TITLE
Nexus 1.1.0 wont start core on windows 10

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [Nexusoft/NexusInterface#60]
to reproduce:
install newest wallet 1.1.0 and remove any old "nexus" folders in AppData/Roaming. Create Nexus folder, and copy wallet.dat backup into folder. Once starting the new wallet all other folders are created but gets stuck at "loading core".

Sidenote:
I think its simply a connection error between the core and interface, as I have been running a self built 3.0.2 on windows without any issues.

From the logfile:
`[2019-07-20 12:25:27.425] [info] Checking if core binary exists: C:\Program Files\Nexus\Nexus Wallet\resources\assets\win32\cores\nexus-win32-x64.exe  

[2019-07-20 12:25:27.428] [info] Core binary does not exist: C:\Program Files\Nexus\Nexus Wallet\resources\assets\win32\cores\nexus-win32-x64.exe  

[2019-07-20 12:25:27.429] [info] Core Manager: Core not found, please run in manual deamon mode`

**Comment by KenCorma** [comment]
Please go to https://github.com/Nexusoft/NexusInterface/releases/tag/v1.1.0
New installer is up.
