### ISSUE TITLE
OSX 1.10 stake rate not truncated.

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [Nexusoft/NexusInterface#62]
Just testing the new mac wallet and it works great. No actual issues so far, just one small aesthetic bug.

When staking, the stake rate used to be normalized to 6 decimal places, now it seems to just continue running to the edge of the wallet.

![Screen Shot 2019-07-21 at 4 08 52 PM](https://user-images.githubusercontent.com/5361759/61596487-5b9cdf00-abd2-11e9-99c3-89112b12bab9.png)

**Comment by Qrysto** [comment]
This issue will be fixed in the next 1.2.0 release
