### ISSUE TITLE
No message when finished downloading bootstrap and start unpacking 

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#69]
Derived from bug #56 

![2019-08-08 19_56_17-Debian Buster (Snapshot 1)  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/1646393/62729809-9e561800-ba16-11e9-80a4-4d14e65769d6.png)

OK I downloaded whole bootstrap, 3.83GB. Now it's stuck on Downloading the database... 100%.
In the background, Core continues to sync blocks relentlessly, 35k blocks synced.

I can only click Abort bootstrapping, nothing else is happening.

Upon finished downloading there should be a message - unpacking! Must be added, as this process can take as long as downloading did as users are unaware what is going on and they can just kill it after 15 minutes hanging.
And core must be stopped while bootstrap is being downloaded (this is reported as separate bug #68).

**Comment by l8nit3tr0ubl3** [comment]
if your watching it very closely, the message does switch to "Decompressing the database..." but only for a few seconds before reverting to the Download message. Im looking for the source of the revert, but haven't found anything yet.

**Comment by pioruns** [comment]
I am testing nexus_wallet-Linux-1.2.0.AppImage, issue still exists in this build.

**Comment by Qrysto** [comment]
I've tested but could not reproduce this issue. Bootstrap goes through without any problem for me. @KenCorma could you try to reproduce this?

**Comment by pioruns** [comment]
"Bootstrap went through without any problem for me. "

You saying that "Decompressing database..." is present during decompressing? Because what I've seen and what L8nit3tr0ubl3 confirmed, there is "Downloading the database... 100%" for several minutes during decompressing (that should be fixed and should show Decompressing message).

**Comment by l8nit3tr0ubl3** [comment]
The message does switch briefly to 'decompressing' but reverts back to downloading 100%. Its not the bootstrapping process that has an issue, just the display of progress.

**Comment by KenCorma** [comment]
So would you say this is more of a visual issue or that the bootstrap does not extract properly?

**Comment by pioruns** [comment]
It's 100% visual issue - bootstrap decompressing is done in the background correctly, but user has no notification of this process happening and he still see "Downloading...100%" for several minutes.
