### ISSUE TITLE
Transactions tab doesn't work

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#82]
Transactions tab doesn't work - I have loaded the wallet with hundreds of Txs, balance valid, unlocked and staking active, but Transactions tab is stuck on "loading" (been waiting several minutes). Using latest .deb on Debian Linux

![2019-08-11 12_17_17-nv01 VNC](https://user-images.githubusercontent.com/1646393/62833164-15b3c380-bc32-11e9-83f6-6adea55c6dc8.png)

**Comment by Qrysto** [comment]
@pioruns Could you help me turn on Developer Mode (in Settings/Application), then open DevTools (menu View/Toggle Developer Tools), and see what error it had?

**Comment by pioruns** [comment]
I tried to reproduce the error but so far without luck - it's currently working OK.
