### ISSUE TITLE
Missing 'more details' in trasaction menu.

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [Nexusoft/NexusInterface#84]
**Describe the bug**
Windows 10, 1.2.0 interface, 3.0.3 core. Unable to view 'more details' on transaction page. Right click seems to have no effect, no matter the type or maturity of the transaction. I have tried 3 different PC's with 3 different wallets.

**Expected behavior**
In earlier revisions of the wallet, a drop down menu appeared when right-clicking in the transactions tab. This allowed to view more detailed information of the desired transaction.

**Comment by Qrysto** [comment]
It is supposed to show the Transaction details modal with just a left click on the transaction, but the feature was accidentally broken in 1.2.0 when fixing another bug. This is already fixed in the Merging branch and will be included in the next release.

**Comment by l8nit3tr0ubl3** [comment]
I did try both left and right click, but glad to know you guys were already on top of it!  Best dev team in the crypto-space by far!

**Comment by l8nit3tr0ubl3** [comment]
Tested the Merging 1.2.1 wallet, all fixed as you said! Closing now.
