### ISSUE TITLE
nexus_wallet-Linux-1.2.4.AppImage stuck on 99% sync - block 2920066

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#94]
Been running nexus_wallet-Linux-1.2.3.AppImage for some time. Today upgraded to new version nexus_wallet-Linux-1.2.4.AppImage. After restart, wallet is stuck at 99% synchronisation, block 2920066. Restarts doesn't change anything.
[0.log](https://github.com/Nexusoft/NexusInterface/files/3801949/0.log)

**Comment by pioruns** [comment]
Console output:
![image](https://user-images.githubusercontent.com/1646393/68090088-c3b4bf80-fe67-11e9-87b5-2c7e6520b9c7.png)

**Comment by pioruns** [comment]
GUI window
![image](https://user-images.githubusercontent.com/1646393/68090102-e1822480-fe67-11e9-85d2-484dec0c913d.png)

**Comment by pioruns** [comment]
New 0.log attached (after restart)


[0.log](https://github.com/Nexusoft/NexusInterface/files/3801970/0.log)

**Comment by KenCorma** [comment]
If you are stuck on 2920066 you are on a bad chain. Please re download the database and let me know.

**Comment by pioruns** [comment]
And why would by client ended up on "bad" chain? I thought client should pick correct chain automatically?

**Comment by KenCorma** [comment]
I understand that concern and I apologize that these issue have come up. This is still using all the, what we consider, legacy code. Our new code with Tritium is being rolled out in the coming weeks.  It will be easier for now on for people to be in sync.

**Comment by pioruns** [comment]
Fantastic. Don't get me wrong, I am here not to moan but to let you know about issues and to report these things whatever they are.

**Comment by KenCorma** [comment]
Yeah I understand, we wont know about something unless people report it.

**Comment by ericmuyser** [comment]
I'm stuck on 98% on Tritium, fresh download & upgrade, clicked the "upgrade database" thing and downloaded 40gb.

**Comment by Qrysto** [comment]
@ericmuyser how long have you been at 98%, and if you hover your mouse on Block Count (in Overview page), what's the "last updated"?
