### ISSUE TITLE
After bootstrap, "Nexus is stuck on Connecting to Nexus Core..."

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#95]
Just bootstrapped Nexus, because it was stuck on some random block.
Bootstrapping process just finished with success, all I can see now is:
![image](https://user-images.githubusercontent.com/1646393/68090648-feb9f180-fe6d-11e9-8ab2-d8c07ddaa1be.png)
![image](https://user-images.githubusercontent.com/1646393/68090650-037ea580-fe6e-11e9-8663-c3a105789dfe.png)
[0.log](https://github.com/Nexusoft/NexusInterface/files/3802004/0.log)
Using latest 1.2.4 AppImage.

**Comment by pioruns** [comment]
When stopped, I noticed new output in command line:
```
Core Manager: Stop function called
Core Manager: Core has already stopped.
```

I guess Core should not asked if not called to.

**Comment by pioruns** [comment]
Once restarted, Nexus finally got itself synchronized 100%.

**Comment by KenCorma** [comment]
Please shut down nexus, delete all the logs and then restart  the UI ( so that the logs can be blank ) and post it.

**Comment by pioruns** [comment]
I restarted the wallet and it started just fine. My balance was wrong so I had to click Reload transaction history from the menu.
Why would it not start correctly on the first time?

**Comment by pioruns** [comment]
[0.log](https://github.com/Nexusoft/NexusInterface/files/3803213/0.log)
